name: Code Coverage

on:
  push:
    branches: [ master ]
    paths:
      - 'config/*'
      - 'src/**'
      - 'tests/**'
      - 'phpunit.xml'
      - 'composer.*'
  pull_request:
    branches: [ master ]
    paths:
      - 'config/*'
      - 'src/**'
      - 'tests/**'
      - 'phpunit.xml'
      - 'composer.*'

jobs:
  code-cov:
    runs-on: ubuntu-latest
    name: Code coverage report
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: dom, curl, libxml, mbstring, zip
          tools: composer:v2
          coverage: xdebug

      - name: Install dependencies
        run: |
          composer install --no-plugins --no-scripts --no-interaction --no-progress --prefer-dist

      - name: Execute tests
        run: vendor/bin/phpunit --coverage-clover coverage.xml

      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
