name: Laravel IRL tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ 7.2, 7.3, 7.4, 8.0 ]
        laravel: [ ^6.0, ^7.0, ^8.0 ]
        exclude:
          - php: 7.2
            laravel: ^8.0
          - php: 8.0
            laravel: ^6.0
          - php: 8.0
            laravel: ^7.0

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: 'console-logg-package'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          tools: composer:v2
          coverage: none

      - name: Install console-logg dependencies
        run: |
          cd console-logg-package
          composer install --no-plugins --no-scripts --no-interaction --no-progress --prefer-dist

      - name: Setup Laravel application
        run: |
          composer create-project --prefer-dist laravel/laravel:${{ matrix.laravel }} laravel-app
          cd laravel-app

      - name: Add local path composer dependency
        run: |
          cd laravel-app
          export PHPV=$(php -r "echo implode('.', [PHP_MAJOR_VERSION, PHP_MINOR_VERSION, PHP_RELEASE_VERSION]);")
          cat <<< $(jq '.repositories[0].type="path"' composer.json) > composer.json
          cat <<< $(jq '.repositories[0].url="../console-logg-package"' composer.json) > composer.json
          cat <<< $(jq '.require."devthis/console-logg"="*"' composer.json) > composer.json
          cat <<< $(jq '.require."psr/log"="1.1.4"' composer.json) > composer.json
          cat <<< $(jq -n --arg phpv "$PHPV" '.config.platform.php=$phpv' composer.json) > composer.json
          cat <<< $(jq '.extra.symfony.require="5.4"' composer.json) > composer.json
          cat <<< $(jq '.require.php="^${{ matrix.php }}"' composer.json) > composer.json

      - name: Copy fixtures into Laravel app
        run: |
          mkdir -p laravel-app/app/Console/Commands
          cp console-logg-package/tests/Fixtures/ArtisanCommand.php laravel-app/app/Console/Commands/
          cp console-logg-package/tests/Fixtures/ServiceThatLoggs.php laravel-app/app/

      - name: Run Laravel package discovery
        run: |
          cd laravel-app
          ls -lha
          cat composer.json
          composer install --no-interaction --no-progress --with-all-dependencies
          php artisan package:discover --ansi
          php artisan clear-compiled

      - name: Run PHPT
        run: |
          cd console-logg-package
          vendor/bin/phpunit tests/PhpTestCase/ --testdox
