name: Laravel IRL tests

on:
  push:
    branches: [ laravel-irl-tests ]
    paths:
      - 'config/*'
      - 'src/**'
      - 'tests/**'
      - 'phpunit.xml'
      - 'composer.*'
  pull_request:
    branches: [ laravel-irl-tests ]
    paths:
      - 'config/*'
      - 'src/**'
      - 'tests/**'
      - 'phpunit.xml'
      - 'composer.*'

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ 7.4 ] #, 7.3, 7.4 ]
        laravel: [ ^8.0 ] # ^7.0, ^8.0 ]
        exclude:
          - php: 7.2
            laravel: ^8.0

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: 'console-logg-package'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          tools: composer:v2
          coverage: none

      - name: Setup structure
        run: |
          composer create-project --prefer-dist laravel/laravel:^7.0 laravel-app
          cd laravel-app

      - name: Tesat
        run: |
          cd laravel-app
          $(cat composer.json | jq '.repositories[0].type="path"') > composer.json
          $(cat composer.json | jq '.repositories[0].url="../console-logg-package"') > composer.json
          $(cat composer.json | jq '.require."devthis/console-logg"="*"') > composer.json
          ls -lha
          composer install
