name: PHPUnit suite

on:
  push:
    branches: [ master ]
    paths:
      - 'config/*'
      - 'src/**'
      - 'tests/**'
      - 'phpunit.xml'
      - 'composer.*'
  pull_request:
    branches: [ master ]
    paths:
      - 'config/*'
      - 'src/**'
      - 'tests/**'
      - 'phpunit.xml'
      - 'composer.*'

jobs:
  phpunit-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: 7.2
            laravel: ^6.0
          - php: 7.3
            laravel: ^6.0
          - php: 7.4
            laravel: ^6.0
          - php: 7.2
            laravel: ^7.0
          - php: 7.3
            laravel: ^7.0
          - php: 7.4
            laravel: ^7.0
          - php: 8.0
            laravel: ^7.0
          - php: 7.3
            laravel: ^8.0
          - php: 7.4
            laravel: ^8.0
          - php: 8.1
            laravel: ^8.0
          - php: 8.1
            laravel: ^9.0

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: |
          composer require "illuminate/contracts=${{ matrix.laravel }}" --no-plugins --no-scripts --no-interaction --no-progress --prefer-dist
          composer update --no-plugins --no-scripts --no-interaction --no-progress --prefer-dist

      - name: Configure matchers
        uses: mheap/phpunit-matcher-action@v1

      - name: Execute tests
        run: vendor/bin/phpunit --teamcity
